version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    on-failure: CONTINUE
    commands:
      - echo pre-build
  build:
    on-failure: ABORT
    commands:
      - mvn clean package
      - echo build
  post_build:
    on-failure: CONTINUE
    commands:
      - echo post-build

artifacts:
  files:
    - target/todo-rest-api-h2-0.0.1.jar
